export {default as NotFound}  from './NotFound';
export {default as ShoppingCartPage} from './cartPage/ShoppingCartPage';
export {default as ShopPage} from './shopPage/ShopPage';
export {default as AboutUsPage } from './aboutUsPage/AboutUsPage';
export {default as ContactPage} from './contactPage/ContactPage';
export {default as BookingPage} from './bookingPage/BookingPage';
export {default as UserLayout} from './UserLayout'
export {default as HomePage} from './homepage/Homepage'
export {default as LoginPage} from './auth/LoginPage'
export {default as SignupPage} from './auth/SignupPage'
export {default as CheckOutPage} from './checkOutPage/CheckOutPage'
export {default as ProductDetailsPage} from './productDetailsPage/ProductDetailsPage'
export {default as ScrollToTop} from './ScrollToTop'
export {default as WishListPage} from './wishListPage/WishListPage'
export {default as VerifyBookingPage} from './bookingPage/VerifyBookingPage'
export {default as RequireAuth} from './auth/RequireAuth'
export {default as OrderHistoryPage} from './orderHistoryPage/OrderHistoryPage'
export {default as WalletPage} from './wallet/WalletPage'
export {default as CustomeOrderPage} from './orderCustomPage/CustomOrderPage'
