export const ICON_PRE_STYLE = 'h-6 w-6'

export {default as GearIcon} from './GearIcon.jsx'
export {default as ShoppingCartIcon} from './ShoppingCartIcon.jsx'
export {default as MagnifyingGlassIcon} from './MagnifyingGlassIcon.jsx'
export {default as ArrowRightIcon} from './ArrowRightIcon.jsx'
export {default as SquaresIcon} from './SquaresIcon.jsx'
export {default as RowViewIcon} from './RowViewIcon.jsx'
export {default as ChevronDown} from './ChevronDown.jsx'
export {default as GoogleIcon} from './GoogleIcon.jsx'
export {default as UserIcon} from './UserIcon.jsx'